### ISSUE TITLE
Doesn't set UTF-8 header

### ISSUE THREAD

**Issue by 602p** [acmumn/paste-acm#1]
It sets the `content-type` header to `text/plain`, not `text/plain; charset=utf-8` and so some utf-8 pastes don't work right.

Currently worked-around in "prod" with `add_header "content-type" "text/plain; charset=utf-8";` in nginx, but should be set in the server itself.

**Comment by iptq** [comment]
this should do it https://github.com/acmumn/paste-acm/commit/78914884627558710737d37bd36713871f7fa0eb#diff-85e4512925333b8295ca384b8a74f8d1L28
