### ISSUE TITLE
Use remote database

### ISSUE THREAD

**Issue by 602p** [acmumn/paste-acm#2]
If argo reboots we eat it. This isn't a big issue (we made no promise that stuff _dosen't_ get nuked) but it would be good if we at least had the option for this to use a persistent db (w/o mounting one into the container, at least.)

**Comment by remexre** [comment]
Uh, if argo reboots we're still fine; one would have to explicitly delete
the Docker container.

**Comment by 602p** [comment]
d; ok; ty.
I don't know how docker works, I just use it.

**Comment by iptq** [comment]
Do we want to support arbitrary databases? Otherwise we could just mount the sqlite file into the container as a volume if we just want persistence outside of the container.

**Comment by iptq** [comment]
it's mounted, i think that's good enough for now
